# all my servers : mlfow & streamlit(need Dockerfile) 
# all my servers : mlflow - streamlit:Dockerfile 

version: '3.8'

# servers 
services: 
  # streamit server
  streamit:
    build: 
      context: . # المسار 
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - mlflow

  # mlflow server
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 